# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
        ('construction', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CONTRACT', 'Contrat'), ('PLAN', 'Plan / architecture'), ('QUOTE', 'Devis'), ('INVOICE', 'Facture'), ('PERMIT', 'Autorisation / titre foncier'), ('REPORT', 'Rapport'), ('HANDOVER', 'Procès-verbal de réception'), ('OTHER', 'Autre')], default='OTHER', max_length=12, verbose_name='type')),
                ('title', models.CharField(max_length=180, verbose_name='intitulé')),
                ('visible_to_customer', models.BooleanField(default=True, verbose_name='visible par le client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document de projet',
                'verbose_name_plural': 'documents de projet',
                'ordering': ('kind', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Chargé de suivi KEMTA'), ('SUPERVISOR', 'Superviseur technique'), ('FIELD', 'Technicien terrain'), ('FINANCE', 'Contrôleur financier'), ('CLIENT_PROXY', 'Représentant du client'), ('OBSERVER', 'Observateur')], default='FIELD', max_length=16, verbose_name='rôle')),
                ('can_capture_evidence', models.BooleanField(default=True, verbose_name='peut publier des preuves')),
                ('can_validate_evidence', models.BooleanField(default=False, verbose_name='peut valider des preuves')),
                ('can_view_finance', models.BooleanField(default=False, verbose_name='accès aux finances')),
                ('can_manage_schedule', models.BooleanField(default=False, verbose_name='gère le planning')),
                ('receives_notifications', models.BooleanField(default=True, verbose_name='reçoit les notifications')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='a rejoint le')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='retiré le')),
            ],
            options={
                'verbose_name': 'membre de projet',
                'verbose_name_plural': 'membres de projet',
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('NOTE', 'Note de suivi'), ('PROGRESS', 'Avancement'), ('PHASE', 'Étape du chantier'), ('TASK', 'Tâche'), ('EVIDENCE', 'Preuve terrain'), ('REPORT', 'Rapport'), ('FINANCE', 'Finance'), ('INCIDENT', 'Incident / alerte'), ('MILESTONE', 'Jalon majeur'), ('DOCUMENT', 'Document partagé'), ('COMMENT', 'Commentaire client')], default='NOTE', max_length=12, verbose_name='type')),
                ('message', models.TextField(verbose_name='message')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='données')),
                ('visibility', models.CharField(choices=[('CUSTOMER', 'Client et équipe'), ('TEAM', 'Équipe KEMTA'), ('PUBLIC', 'Public')], default='CUSTOMER', max_length=10, verbose_name='visibilité')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'mise à jour de projet',
                'verbose_name_plural': 'mises à jour de projet',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='intitulé')),
                ('description', models.TextField(blank=True, verbose_name='détail')),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('BLOCKED', 'Bloquée'), ('DONE', 'Terminée'), ('CANCELLED', 'Annulée')], db_index=True, default='TODO', max_length=12, verbose_name='statut')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('NORMAL', 'Normale'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='NORMAL', max_length=8, verbose_name='priorité')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='échéance')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='démarrée le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('requires_evidence', models.BooleanField(default=False, verbose_name='preuve photo requise')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='avancement (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tâche',
                'verbose_name_plural': 'tâches',
                'ordering': ('order', 'due_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATERIAUX', 'Matériaux'), ('MAIN_OEUVRE', "Main-d'œuvre"), ('TRANSPORT', 'Transport et logistique'), ('LOCATION', 'Location de matériel'), ('ETUDES', 'Études et honoraires'), ('ADMINISTRATIF', 'Frais administratifs'), ('DIVERS', 'Divers')], default='MATERIAUX', max_length=16, verbose_name='catégorie')),
                ('label', models.CharField(max_length=180, verbose_name='libellé')),
                ('planned_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prévu (FCFA)')),
                ('committed_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='commandé (FCFA)')),
                ('spent_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='payé (FCFA)')),
                ('supplier', models.CharField(blank=True, max_length=180, verbose_name='fournisseur')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='construction.phase', verbose_name='phase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ligne budgétaire',
                'verbose_name_plural': 'lignes budgétaires',
                'ordering': ('category', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('name', models.CharField(max_length=200, verbose_name='nom du projet')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='adresse')),
                ('kind', models.CharField(choices=[('BUILD', 'Construction neuve'), ('FOLLOW_UP', 'Suivi de chantier existant'), ('MAINTENANCE', 'Entretien / réhabilitation'), ('STUDY', 'Étude et faisabilité')], default='BUILD', max_length=16, verbose_name='nature')),
                ('location_text', models.CharField(blank=True, max_length=200, verbose_name='localisation affichée')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse / repère')),
                ('country', models.CharField(choices=[('CM', 'Cameroun'), ('FR', 'France'), ('BE', 'Belgique'), ('US', 'États-Unis'), ('CA', 'Canada'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('CH', 'Suisse'), ('GA', 'Gabon'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('NG', 'Nigeria'), ('GQ', 'Guinée équatoriale'), ('TD', 'Tchad'), ('OT', 'Autre')], default='CM', max_length=2, verbose_name='pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('DRAFT', 'Préparation'), ('PLANNING', 'Planification'), ('IN_PROGRESS', 'Travaux en cours'), ('ON_HOLD', 'Travaux suspendus'), ('HANDOVER', 'Réception en cours'), ('COMPLETED', 'Livré'), ('CANCELLED', 'Annulé')], db_index=True, default='DRAFT', max_length=16, verbose_name='statut')),
                ('health', models.CharField(choices=[('ON_TRACK', 'Dans les délais'), ('WATCH', 'À surveiller'), ('AT_RISK', 'En difficulté'), ('COMPLETED', 'Terminé')], default='ON_TRACK', max_length=12, verbose_name='santé du chantier')),
                ('health_notes', models.CharField(blank=True, max_length=255, verbose_name='explication de la santé')),
                ('physical_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='avancement physique (%)')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA (XAF)'), ('EUR', 'Euro'), ('USD', 'Dollar américain')], default='XAF', max_length=3, verbose_name='devise')),
                ('budget_total_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget total (FCFA)')),
                ('budget_spent_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='dépenses engagées (FCFA)')),
                ('contract_signed', models.BooleanField(default=False, verbose_name='contrat signé')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='démarrage prévu')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='livraison prévue')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='démarrage effectif')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='livraison effective')),
                ('next_visit_at', models.DateTimeField(blank=True, null=True, verbose_name='prochaine visite')),
                ('customer_can_comment', models.BooleanField(default=True, verbose_name='le client peut commenter')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='companies.company', verbose_name='entreprise BTP retenue')),
                ('contract_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contracts', to='common.asset', verbose_name='contrat')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_covers', to='common.asset', verbose_name='photo de couverture')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='common.location', verbose_name='localisation')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='chargé de suivi KEMTA')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='properties.property', verbose_name='propriété concernée')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ('-created_at',),
            },
        ),
    ]
