# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app', models.BooleanField(default=True, verbose_name="notifications dans l'application")),
                ('sms', models.BooleanField(default=True, verbose_name='notifications par SMS')),
                ('email', models.BooleanField(default=True, verbose_name='notifications par e-mail')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='notifications WhatsApp')),
                ('project_updates', models.BooleanField(default=True, verbose_name='avancement des chantiers')),
                ('evidence_validated', models.BooleanField(default=True, verbose_name='validation des preuves terrain')),
                ('task_reminders', models.BooleanField(default=True, verbose_name='rappels de tâches')),
                ('payment_events', models.BooleanField(default=True, verbose_name='paiements et factures')),
                ('subscription_events', models.BooleanField(default=True, verbose_name='abonnements')),
                ('opportunity_alerts', models.BooleanField(default=True, verbose_name='nouvelles opportunités BTP')),
                ('marketing', models.BooleanField(default=False, verbose_name='informations et offres KEMTA')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='début des heures calmes')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='fin des heures calmes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'préférences de notification',
                'verbose_name_plural': 'préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SERVICE_REQUEST', 'Demande de service'), ('PROJECT', 'Projet'), ('TASK', 'Tâche'), ('EVIDENCE', 'Preuve terrain'), ('REPORT', 'Rapport'), ('PAYMENT', 'Paiement'), ('SUBSCRIPTION', 'Abonnement'), ('APPLICATION', 'Candidature'), ('OPPORTUNITY', 'Opportunité'), ('MAINTENANCE', 'Entretien'), ('SECURITY', 'Sécurité'), ('SYSTEM', 'Système')], max_length=20, verbose_name='type')),
                ('channel', models.CharField(choices=[('IN_APP', 'Application'), ('SMS', 'SMS'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp')], max_length=10, verbose_name='canal')),
                ('subject', models.CharField(blank=True, max_length=180, verbose_name='sujet')),
                ('body', models.TextField(help_text='Variables disponibles : {prenom}, {reference}, {projet}, {lien}, {montant}…', verbose_name='gabarit')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'gabarit de notification',
                'verbose_name_plural': 'gabarits de notification',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SERVICE_REQUEST', 'Demande de service'), ('PROJECT', 'Projet'), ('TASK', 'Tâche'), ('EVIDENCE', 'Preuve terrain'), ('REPORT', 'Rapport'), ('PAYMENT', 'Paiement'), ('SUBSCRIPTION', 'Abonnement'), ('APPLICATION', 'Candidature'), ('OPPORTUNITY', 'Opportunité'), ('MAINTENANCE', 'Entretien'), ('SECURITY', 'Sécurité'), ('SYSTEM', 'Système')], db_index=True, default='SYSTEM', max_length=20, verbose_name='type')),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Attention'), ('ERROR', 'Erreur')], default='INFO', max_length=8, verbose_name='niveau')),
                ('channel', models.CharField(choices=[('IN_APP', 'Application'), ('SMS', 'SMS'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp')], default='IN_APP', max_length=10, verbose_name='canal')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('FAILED', 'Échec'), ('READ', 'Lue')], db_index=True, default='PENDING', max_length=8, verbose_name='statut')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('body', models.TextField(verbose_name='message')),
                ('action_url', models.CharField(blank=True, max_length=255, verbose_name="lien d'action")),
                ('action_label', models.CharField(blank=True, max_length=60, verbose_name='libellé du bouton')),
                ('entity_type', models.CharField(blank=True, max_length=40, verbose_name="type d'objet lié")),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name="identifiant d'objet")),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='données')),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text="Empêche d'envoyer deux fois la même alerte (ex. « échéance J-1 »).", max_length=120, verbose_name='clé de déduplication')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='programmée pour')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyée le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('failed_reason', models.CharField(blank=True, max_length=255, verbose_name="motif d'échec")),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('provider_reference', models.CharField(blank=True, max_length=120, verbose_name='référence opérateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitted_notifications', to=settings.AUTH_USER_MODEL, verbose_name='émise par')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created_at',),
            },
        ),
    ]
