# Generated by Django 5.1.6 on 2026-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SERVICE_REQUEST', 'Demande de service'), ('PROJECT', 'Projet'), ('TASK', 'Tâche'), ('EVIDENCE', 'Preuve terrain'), ('REPORT', 'Rapport'), ('PAYMENT', 'Paiement'), ('SUBSCRIPTION', 'Abonnement'), ('APPLICATION', 'Candidature'), ('COMPANY', 'Entreprise'), ('OPPORTUNITY', 'Opportunité'), ('MAINTENANCE', 'Entretien'), ('SECURITY', 'Sécurité'), ('SYSTEM', 'Système')], db_index=True, default='SYSTEM', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('SERVICE_REQUEST', 'Demande de service'), ('PROJECT', 'Projet'), ('TASK', 'Tâche'), ('EVIDENCE', 'Preuve terrain'), ('REPORT', 'Rapport'), ('PAYMENT', 'Paiement'), ('SUBSCRIPTION', 'Abonnement'), ('APPLICATION', 'Candidature'), ('COMPANY', 'Entreprise'), ('OPPORTUNITY', 'Opportunité'), ('MAINTENANCE', 'Entretien'), ('SECURITY', 'Sécurité'), ('SYSTEM', 'Système')], max_length=20, verbose_name='type'),
        ),
    ]
