# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=140, verbose_name='nom du service')),
                ('tagline', models.CharField(blank=True, max_length=220, verbose_name='accroche')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icône')),
                ('deliverables', models.JSONField(blank=True, default=list, verbose_name='livrables')),
                ('base_price_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='à partir de (FCFA)')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée indicative (jours)')),
                ('requires_site_visit', models.BooleanField(default=True, verbose_name='visite de site nécessaire')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_heroes', to='common.asset', verbose_name='visuel')),
            ],
            options={
                'verbose_name': 'service KEMTA',
                'verbose_name_plural': 'services KEMTA',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('kind', models.CharField(choices=[('BUILD_PROJECT', 'Construire un projet'), ('EXISTING_SITE', 'Suivre un chantier existant'), ('MAINTENANCE', 'Entretenir une propriété'), ('OTHER', 'Autre besoin')], db_index=True, max_length=20, verbose_name='service demandé')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail (facultatif)')),
                ('country', models.CharField(choices=[('CM', 'Cameroun'), ('FR', 'France'), ('BE', 'Belgique'), ('US', 'États-Unis'), ('CA', 'Canada'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('CH', 'Suisse'), ('GA', 'Gabon'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('NG', 'Nigeria'), ('GQ', 'Guinée équatoriale'), ('TD', 'Tchad'), ('OT', 'Autre')], default='CM', max_length=2, verbose_name='pays')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('city_of_residence', models.CharField(blank=True, max_length=120, verbose_name='ville de résidence')),
                ('project_type', models.CharField(blank=True, max_length=80, verbose_name='type de projet')),
                ('location_text', models.CharField(blank=True, max_length=200, verbose_name='localisation saisie')),
                ('budget_min_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget minimum (FCFA)')),
                ('budget_max_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget maximum (FCFA)')),
                ('spent_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget déjà engagé (FCFA)')),
                ('desired_start_date', models.DateField(blank=True, null=True, verbose_name='date souhaitée')),
                ('description', models.TextField(blank=True, verbose_name='description du besoin')),
                ('current_progress', models.CharField(blank=True, max_length=120, verbose_name="niveau d'avancement")),
                ('current_company', models.CharField(blank=True, max_length=180, verbose_name='entreprise actuelle')),
                ('site_manager', models.CharField(blank=True, max_length=180, verbose_name='chef de chantier')),
                ('known_issues', models.TextField(blank=True, verbose_name='problèmes rencontrés')),
                ('objective', models.TextField(blank=True, verbose_name='objectif recherché')),
                ('maintenance_services', models.JSONField(blank=True, default=list, verbose_name='prestations souhaitées')),
                ('maintenance_frequency', models.CharField(blank=True, max_length=20, verbose_name='fréquence souhaitée')),
                ('property_type', models.CharField(blank=True, max_length=40, verbose_name='type de propriété')),
                ('property_occupied', models.CharField(blank=True, max_length=20, verbose_name='propriété occupée')),
                ('last_visit_date', models.DateField(blank=True, null=True, verbose_name='dernière visite')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Réponses brutes du formulaire dynamique (multi-étapes).', verbose_name='réponses du formulaire')),
                ('source', models.CharField(default='site', max_length=40, verbose_name='origine')),
                ('utm', models.JSONField(blank=True, default=dict, verbose_name='campagne')),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('REVIEWING', "En cours d'étude"), ('QUALIFIED', 'Qualifiée'), ('CONTACTED', 'Client contacté'), ('MEETING', 'Rendez-vous programmé'), ('CONVERTED', 'Convertie en projet'), ('REJECTED', 'Non retenue'), ('CLOSED', 'Clôturée')], db_index=True, default='NEW', max_length=16, verbose_name='statut')),
                ('priority', models.PositiveSmallIntegerField(default=2, help_text='1 = haute, 3 = basse', verbose_name='priorité')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('estimated_value_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valeur estimée (FCFA)')),
                ('qualification_notes', models.TextField(blank=True, verbose_name='notes de qualification')),
                ('scheduled_call_at', models.DateTimeField(blank=True, null=True, verbose_name='appel programmé')),
                ('first_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='premier contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='reçue le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='chargé de suivi')),
                ('converted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='projects.project', verbose_name='projet créé')),
                ('converted_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='properties.property', verbose_name='propriété enregistrée')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='common.location', verbose_name='localisation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='service_requests.servicecatalog', verbose_name='service catalogue')),
            ],
            options={
                'verbose_name': 'demande de service',
                'verbose_name_plural': 'demandes de service',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PHOTO', 'Photo du site'), ('PLAN', 'Plan / croquis'), ('DOCUMENT', 'Document'), ('QUOTE', 'Devis existant')], default='PHOTO', max_length=12, verbose_name='catégorie')),
                ('caption', models.CharField(blank=True, max_length=180, verbose_name='légende')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_attachments', to='common.asset', verbose_name='fichier')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_requests.servicerequest', verbose_name='demande')),
            ],
            options={
                'verbose_name': 'pièce jointe de demande',
                'verbose_name_plural': 'pièces jointes de demande',
                'ordering': ('category', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=16, verbose_name='statut précédent')),
                ('to_status', models.CharField(blank=True, max_length=16, verbose_name='nouveau statut')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('is_customer_visible', models.BooleanField(default=True, verbose_name='visible par le client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_events', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='service_requests.servicerequest', verbose_name='demande')),
            ],
            options={
                'verbose_name': 'événement de demande',
                'verbose_name_plural': 'événements de demande',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='servicecatalog',
            index=models.Index(fields=['is_active', 'order'], name='service_req_is_acti_8e0c98_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='service_req_status_7b32fc_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['kind', 'status'], name='service_req_kind_39f6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['phone', '-created_at'], name='service_req_phone_d173d2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestattachment',
            index=models.Index(fields=['request', 'category'], name='service_req_request_2429e8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestevent',
            index=models.Index(fields=['request', '-created_at'], name='service_req_request_db6d62_idx'),
        ),
    ]
