# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='nom de la réalisation')),
                ('slug', models.SlugField(max_length=220, verbose_name='adresse')),
                ('realization_type', models.CharField(choices=[('VILLA', 'Villa'), ('MAISON', 'Maison individuelle'), ('IMMEUBLE', 'Immeuble'), ('APPARTEMENT', "Immeuble d'appartements"), ('LOCAL_COMMERCIAL', 'Local commercial'), ('BUREAU', 'Bureaux'), ('ECOLE', 'Établissement scolaire'), ('SANTE', 'Structure de santé'), ('ROUTE', 'Voirie / route'), ('FORAGE', "Forage / adduction d'eau"), ('RENOVATION', 'Rénovation'), ('AMENAGEMENT', 'Aménagement / VRD'), ('AUTRE', 'Autre')], default='VILLA', max_length=24, verbose_name='type')),
                ('location_text', models.CharField(blank=True, max_length=180, verbose_name='localisation affichée')),
                ('country', models.CharField(choices=[('CM', 'Cameroun'), ('FR', 'France'), ('BE', 'Belgique'), ('US', 'États-Unis'), ('CA', 'Canada'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('CH', 'Suisse'), ('GA', 'Gabon'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('NG', 'Nigeria'), ('GQ', 'Guinée équatoriale'), ('TD', 'Tchad'), ('OT', 'Autre')], default='CM', max_length=2, verbose_name='pays')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='année de livraison')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('surface_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='surface (m²)')),
                ('levels_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nombre de niveaux')),
                ('rooms_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nombre de pièces')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée des travaux (jours)')),
                ('budget_xaf', models.DecimalField(blank=True, decimal_places=2, help_text="Laisser vide si l'entreprise ne souhaite pas publier le budget.", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget (FCFA)')),
                ('budget_visible', models.BooleanField(default=False, verbose_name='afficher le budget publiquement')),
                ('client_testimonial', models.TextField(blank=True, verbose_name='témoignage client')),
                ('client_name', models.CharField(blank=True, max_length=160, verbose_name='client (affiché si autorisé)')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente de validation'), ('PUBLISHED', 'Publiée'), ('REJECTED', 'Refusée'), ('ARCHIVED', 'Archivée')], db_index=True, default='PUBLISHED', max_length=20, verbose_name='statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mise en avant')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='vues')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'réalisation',
                'verbose_name_plural': 'réalisations',
                'ordering': ('order', '-year', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RealizationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PHOTO', 'Photo'), ('BEFORE', 'Avant travaux'), ('AFTER', 'Après travaux'), ('VIDEO', 'Vidéo'), ('PLAN', 'Plan / schéma')], default='PHOTO', max_length=10, verbose_name='type')),
                ('caption', models.CharField(blank=True, max_length=180, verbose_name='légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'média de réalisation',
                'verbose_name_plural': 'médias de réalisation',
                'ordering': ('order', 'id'),
            },
        ),
    ]
