# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('btp_catalog', '0001_initial'),
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realization',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='companies.company', verbose_name='entreprise'),
        ),
        migrations.AddField(
            model_name='realization',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realization_covers', to='common.asset', verbose_name='photo principale'),
        ),
        migrations.AddField(
            model_name='realization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créée par'),
        ),
        migrations.AddField(
            model_name='realization',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizations', to='common.location', verbose_name='localisation'),
        ),
        migrations.AddField(
            model_name='realization',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='realizations', to='companies.specialty', verbose_name='services réalisés'),
        ),
        migrations.AddField(
            model_name='realizationmedia',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realization_media', to='common.asset', verbose_name='fichier'),
        ),
        migrations.AddField(
            model_name='realizationmedia',
            name='realization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='btp_catalog.realization', verbose_name='réalisation'),
        ),
        migrations.AddIndex(
            model_name='realization',
            index=models.Index(fields=['status', 'is_featured', '-year'], name='btp_catalog_status_b9edc1_idx'),
        ),
        migrations.AddIndex(
            model_name='realization',
            index=models.Index(fields=['realization_type', 'status'], name='btp_catalog_realiza_93efd1_idx'),
        ),
        migrations.AddIndex(
            model_name='realization',
            index=models.Index(fields=['company', 'status'], name='btp_catalog_company_588c44_idx'),
        ),
        migrations.AddConstraint(
            model_name='realization',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='uniq_realization_slug_per_company'),
        ),
        migrations.AddIndex(
            model_name='realizationmedia',
            index=models.Index(fields=['realization', 'kind', 'order'], name='btp_catalog_realiza_3c2d5a_idx'),
        ),
    ]
