# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name="nom de l'étape")),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('weight_percent', models.DecimalField(decimal_places=2, default=0, help_text='Part de cette étape dans le volume global de travaux.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="poids dans l'avancement (%)")),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='avancement (%)')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non démarrée'), ('IN_PROGRESS', 'En cours'), ('BLOCKED', 'Bloquée'), ('DONE', 'Terminée'), ('CANCELLED', 'Annulée')], db_index=True, default='NOT_STARTED', max_length=12, verbose_name='statut')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='début prévu')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='fin prévue')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='début effectif')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='fin effective')),
                ('budget_planned_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget prévu (FCFA)')),
                ('budget_spent_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='dépensé (FCFA)')),
                ('blocked_reason', models.CharField(blank=True, max_length=255, verbose_name='motif du blocage')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'phase de chantier',
                'verbose_name_plural': 'phases de chantier',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PhaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='nom du modèle')),
                ('kind', models.CharField(blank=True, max_length=16, verbose_name='nature de projet')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('steps', models.JSONField(default=list, help_text='Liste [{name, weight_percent, duration_days, description}]', verbose_name='étapes')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'modèle de phases',
                'verbose_name_plural': 'modèles de phases',
                'ordering': ('name',),
            },
        ),
    ]
