# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='projet'),
        ),
        migrations.AddField(
            model_name='phase',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AddIndex(
            model_name='phase',
            index=models.Index(fields=['project', 'order'], name='constructio_project_6d49cd_idx'),
        ),
        migrations.AddIndex(
            model_name='phase',
            index=models.Index(fields=['project', 'status'], name='constructio_project_847b6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_phase_name_per_project'),
        ),
    ]
