# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='libellé')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icône')),
                ('base_price_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tarif indicatif (FCFA)')),
                ('unit', models.CharField(default='intervention', max_length=40, verbose_name='unité')),
                ('requires_technician', models.BooleanField(default=False, verbose_name='nécessite un technicien')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': "prestation d'entretien",
                'verbose_name_plural': "prestations d'entretien",
                'ordering': ('order', 'name'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='maintenance_is_acti_744986_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('frequency', models.CharField(choices=[('PUNCTUAL', 'Ponctuelle'), ('MONTHLY', 'Mensuelle'), ('QUARTERLY', 'Trimestrielle'), ('SEMIANNUAL', 'Semestrielle'), ('ANNUAL', 'Annuelle'), ('ON_DEMAND', 'Sur demande')], default='QUARTERLY', max_length=12, verbose_name='fréquence')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('PAUSED', 'En pause'), ('ENDED', 'Terminé'), ('CANCELLED', 'Annulé')], db_index=True, default='DRAFT', max_length=12, verbose_name='statut')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('price_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant du contrat (FCFA)')),
                ('billing_cycle_months', models.PositiveSmallIntegerField(default=1, verbose_name='facturation (mois)')),
                ('visits_included', models.PositiveSmallIntegerField(default=1, verbose_name='visites incluses')),
                ('auto_generate_visits', models.BooleanField(default=True, verbose_name='planifier automatiquement les visites')),
                ('instructions', models.TextField(blank=True, verbose_name='consignes particulières')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_generated_visit_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière planification')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_contracts', to=settings.AUTH_USER_MODEL, verbose_name='équipe affectée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_contracts', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_contracts', to='properties.property', verbose_name='propriété')),
                ('services', models.ManyToManyField(blank=True, related_name='contracts', to='maintenance.maintenanceservicetype', verbose_name='prestations')),
            ],
            options={
                'verbose_name': "contrat d'entretien",
                'verbose_name_plural': "contrats d'entretien",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('scheduled_for', models.DateTimeField(db_index=True, verbose_name='planifiée le')),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(default=90, verbose_name='durée estimée (min)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='réalisée le')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('CONFIRMED', 'Confirmée'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Réalisée'), ('CANCELLED', 'Annulée'), ('MISSED', 'Non réalisée')], db_index=True, default='SCHEDULED', max_length=12, verbose_name='statut')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='Liste [{label, done, comment}]', verbose_name='points de contrôle')),
                ('report', models.TextField(blank=True, verbose_name='compte rendu')),
                ('customer_visible_report', models.TextField(blank=True, verbose_name='compte rendu client')),
                ('recommendations', models.TextField(blank=True, verbose_name='recommandations')),
                ('issues_found', models.PositiveSmallIntegerField(default=0, verbose_name='problèmes constatés')),
                ('condition_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='état constaté (sur 100)')),
                ('cost_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="coût de l'intervention (FCFA)")),
                ('access_notes', models.CharField(blank=True, max_length=255, verbose_name='accès / clés')),
                ('photos_count', models.PositiveSmallIntegerField(default=0, verbose_name='photos envoyées')),
                ('client_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='client informé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='maintenance.maintenancecontract', verbose_name='contrat')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.property', verbose_name='propriété')),
                ('services_performed', models.ManyToManyField(blank=True, related_name='visits', to='maintenance.maintenanceservicetype', verbose_name='prestations réalisées')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_visits', to=settings.AUTH_USER_MODEL, verbose_name='technicien')),
            ],
            options={
                'verbose_name': "visite d'entretien",
                'verbose_name_plural': "visites d'entretien",
                'ordering': ('-scheduled_for',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='problème')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('severity', models.CharField(choices=[('LOW', 'Mineur'), ('MEDIUM', 'À traiter'), ('HIGH', 'Important'), ('CRITICAL', 'Urgent / sécurité')], default='MEDIUM', max_length=8, verbose_name='gravité')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('QUOTED', 'Devis transmis'), ('APPROVED', 'Validé par le client'), ('SCHEDULED', 'Réparation planifiée'), ('FIXED', 'Réparé'), ('REJECTED', 'Refusé par le client'), ('IGNORED', 'Sans suite')], db_index=True, default='OPEN', max_length=10, verbose_name='statut')),
                ('estimate_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='coût estimé (FCFA)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='résolu le')),
                ('resolution_notes', models.CharField(blank=True, max_length=255, verbose_name='notes de résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_issues', to='common.asset', verbose_name='photo du problème')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='properties.property', verbose_name='propriété')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='signalé par')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='maintenance.maintenancevisit', verbose_name='visite')),
            ],
            options={
                'verbose_name': 'problème constaté',
                'verbose_name_plural': 'problèmes constatés',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='maintenancecontract',
            index=models.Index(fields=['status', '-created_at'], name='maintenance_status_7983be_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancecontract',
            index=models.Index(fields=['customer', 'status'], name='maintenance_custome_990291_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancecontract',
            index=models.Index(fields=['property', 'status'], name='maintenance_propert_d87edb_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancevisit',
            index=models.Index(fields=['status', 'scheduled_for'], name='maintenance_status_0ffe41_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancevisit',
            index=models.Index(fields=['property', '-scheduled_for'], name='maintenance_propert_7474b0_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancevisit',
            index=models.Index(fields=['technician', 'status'], name='maintenance_technic_539bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceissue',
            index=models.Index(fields=['status', 'severity'], name='maintenance_status_63ce92_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceissue',
            index=models.Index(fields=['property', 'status'], name='maintenance_propert_30da5b_idx'),
        ),
    ]
