# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='nom commercial')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='accroche')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix (FCFA)')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA (XAF)'), ('EUR', 'Euro'), ('USD', 'Dollar américain')], default='XAF', max_length=3, verbose_name='devise')),
                ('interval', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('YEARLY', 'Annuel')], default='MONTHLY', max_length=12, verbose_name='périodicité')),
                ('trial_days', models.PositiveSmallIntegerField(default=0, verbose_name="période d'essai (jours)")),
                ('features', models.JSONField(blank=True, default=list, help_text='Liste de chaînes affichées sur la page tarifs.', verbose_name='avantages affichés')),
                ('limits', models.JSONField(blank=True, default=dict, help_text="Ex. {'realizations': 5, 'photos_per_realization': 10, 'applications_per_month': 3, 'featured': false}", verbose_name="limites d'usage")),
                ('is_public', models.BooleanField(default=True, verbose_name='visible publiquement')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "plan d'abonnement",
                'verbose_name_plural': "plans d'abonnement",
                'ordering': ('sort_order', 'price_xaf'),
                'indexes': [models.Index(fields=['is_active', 'is_public', 'sort_order'], name='subscriptio_is_acti_571690_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIALING', "Période d'essai"), ('ACTIVE', 'Actif'), ('PAST_DUE', 'Impayé'), ('CANCELLED', 'Résilié'), ('EXPIRED', 'Expiré')], db_index=True, default='ACTIVE', max_length=12, verbose_name='statut')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='début')),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='période en cours depuis')),
                ('current_period_end', models.DateTimeField(db_index=True, verbose_name="période en cours jusqu'au")),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name="fin d'essai")),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='résilié le')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='résiliation à échéance')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
                ('price_xaf_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Prix figé à la souscription : un changement de tarif ne touche pas les contrats en cours.', max_digits=12, verbose_name='prix contractuel (FCFA)')),
                ('seats', models.PositiveSmallIntegerField(default=1, verbose_name='utilisateurs inclus')),
                ('provider', models.CharField(default='MANUAL', max_length=16, verbose_name='moyen de paiement')),
                ('provider_reference', models.CharField(blank=True, max_length=120, verbose_name='référence fournisseur')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='renouvellement automatique')),
                ('applications_used', models.PositiveIntegerField(default=0, verbose_name='candidatures ce mois')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company', verbose_name='entreprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'current_period_end'], name='subscriptio_status_3d1ac5_idx'), models.Index(fields=['company', 'status'], name='subscriptio_company_c201ce_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['TRIALING', 'ACTIVE', 'PAST_DUE'])), fields=('company',), name='uniq_active_subscription_per_company')],
            },
        ),
    ]
