# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('name', models.CharField(max_length=180, verbose_name='nom du bien')),
                ('property_type', models.CharField(choices=[('VILLA', 'Villa'), ('MAISON', 'Maison'), ('APPARTEMENT', 'Appartement'), ('IMMEUBLE', 'Immeuble'), ('LOCAL_COMMERCIAL', 'Local commercial'), ('BUREAU', 'Bureau'), ('TERRAIN', 'Terrain'), ('ENTREPOT', 'Entrepôt')], default='VILLA', max_length=20, verbose_name='type')),
                ('location_text', models.CharField(blank=True, max_length=200, verbose_name='localisation affichée')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse / repère')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('country', models.CharField(choices=[('CM', 'Cameroun'), ('FR', 'France'), ('BE', 'Belgique'), ('US', 'États-Unis'), ('CA', 'Canada'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('CH', 'Suisse'), ('GA', 'Gabon'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('NG', 'Nigeria'), ('GQ', 'Guinée équatoriale'), ('TD', 'Tchad'), ('OT', 'Autre')], default='CM', max_length=2, verbose_name='pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='surface (m²)')),
                ('land_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='surface du terrain (m²)')),
                ('rooms_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nombre de pièces')),
                ('bedrooms_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='chambres')),
                ('bathrooms_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="salles d'eau")),
                ('levels_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='niveaux')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='année de construction')),
                ('occupancy_status', models.CharField(choices=[('VACANT', 'Inoccupée'), ('OCCUPIED_OWNER', 'Occupée par le propriétaire'), ('RENTED', 'Louée'), ('FAMILY', 'Occupée par la famille'), ('GUARDED', 'Sous gardiennage'), ('UNDER_WORK', 'En travaux')], default='VACANT', max_length=20, verbose_name='occupation')),
                ('tenant_name', models.CharField(blank=True, max_length=180, verbose_name='locataire / occupant')),
                ('tenant_phone', models.CharField(blank=True, max_length=20, verbose_name="téléphone de l'occupant")),
                ('has_guardian', models.BooleanField(default=False, verbose_name='gardien sur place')),
                ('is_fenced', models.BooleanField(default=False, verbose_name='clôturée')),
                ('has_water', models.BooleanField(default=True, verbose_name='eau courante')),
                ('has_electricity', models.BooleanField(default=True, verbose_name='électricité')),
                ('has_security_system', models.BooleanField(default=False, verbose_name='dispositif de sécurité')),
                ('documentation_status', models.CharField(blank=True, help_text='Ex. titre foncier disponible, acte de vente, litige en cours.', max_length=40, verbose_name='situation documentaire')),
                ('title_deed_number', models.CharField(blank=True, max_length=80, verbose_name='numéro de titre')),
                ('estimated_value_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valeur estimée (FCFA)')),
                ('monthly_rent_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='loyer mensuel (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('last_visited_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière visite')),
                ('last_inspection_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière inspection')),
                ('next_visit_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='prochaine visite planifiée')),
                ('condition_score', models.PositiveSmallIntegerField(blank=True, help_text="Note d'état issue de la dernière inspection.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='état général (sur 100)')),
                ('is_active', models.BooleanField(default=True, verbose_name='suivi actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_covers', to='common.asset', verbose_name='photo principale')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='common.location', verbose_name='localisation')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL, verbose_name='chargé de suivi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'propriété',
                'verbose_name_plural': 'propriétés',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('GENERAL', 'Vue générale'), ('INTERIOR', 'Intérieur'), ('ISSUE', 'Problème constaté'), ('REPAIR', 'Réparation'), ('DOCUMENT', 'Document')], default='GENERAL', max_length=10, verbose_name='type')),
                ('caption', models.CharField(blank=True, max_length=180, verbose_name='légende')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='prise le')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_photos', to='common.asset', verbose_name='fichier')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property', verbose_name='propriété')),
            ],
            options={
                'verbose_name': 'photo de propriété',
                'verbose_name_plural': 'photos de propriété',
                'ordering': ('order', '-taken_at'),
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'is_active'], name='properties__owner_i_a56902_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['occupancy_status'], name='properties__occupan_6d3b51_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['next_visit_at'], name='properties__next_vi_c94644_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyphoto',
            index=models.Index(fields=['property', 'kind'], name='properties__propert_de5a76_idx'),
        ),
    ]
