# Generated by Django 5.1.6 on 2026-10-05 20:36

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, help_text='Format international E.164, ex. +237699112233', max_length=20, unique=True, verbose_name='téléphone')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='téléphone vérifié')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Optionnel : sert aux notifications et aux factures.', max_length=254, null=True, unique=True, verbose_name='e-mail (facultatif)')),
                ('country', models.CharField(blank=True, default='CM', max_length=2, verbose_name='pays')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur KEMTA'), ('MANAGER', 'Chargé de suivi KEMTA'), ('FIELD', 'Technicien terrain KEMTA'), ('CUSTOMER', 'Client / propriétaire'), ('COMPANY', 'Entreprise BTP')], default='CUSTOMER', max_length=20, verbose_name='rôle')),
                ('preferred_locale', models.CharField(default='fr', max_length=5, verbose_name='langue')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès administration')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='CGU acceptées le')),
                ('marketing_opt_in', models.BooleanField(default=True, verbose_name='accepte les informations KEMTA')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière activité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='téléphone')),
                ('event', models.CharField(choices=[('OTP_REQUESTED', 'Code demandé'), ('OTP_VERIFIED', 'Code validé'), ('OTP_FAILED', 'Code invalide'), ('OTP_EXPIRED', 'Code expiré'), ('OTP_THROTTLED', 'Demande limitée'), ('REGISTERED', 'Compte créé'), ('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Connexion échouée'), ('LOGOUT', 'Déconnexion'), ('TOKEN_REFRESH', 'Jeton renouvelé'), ('PASSWORD_RESET_REQUESTED', 'Réinitialisation demandée'), ('PASSWORD_RESET_DONE', 'Mot de passe réinitialisé'), ('PASSWORD_CHANGED', 'Mot de passe modifié'), ('ACCOUNT_LOCKED', 'Compte suspendu'), ('PHONE_CHANGED', 'Numéro modifié')], db_index=True, max_length=32, verbose_name='événement')),
                ('success', models.BooleanField(default=True, verbose_name='succès')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='agent utilisateur')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='détail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': "journal d'authentification",
                'verbose_name_plural': "journaux d'authentification",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=64, unique=True, verbose_name='identifiant du jeton')),
                ('device_label', models.CharField(blank=True, max_length=160, verbose_name='appareil')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='agent utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='dernière utilisation')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='révoquée le')),
            ],
            options={
                'verbose_name': "session d'appareil",
                'verbose_name_plural': "sessions d'appareil",
                'ordering': ('-last_used_at',),
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='téléphone')),
                ('purpose', models.CharField(choices=[('REGISTER', 'Inscription'), ('LOGIN', 'Connexion'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe'), ('PHONE_CHANGE', 'Changement de numéro'), ('SENSITIVE_ACTION', 'Action sensible')], db_index=True, max_length=20, verbose_name='objet')),
                ('code_hash', models.CharField(max_length=128, verbose_name='empreinte du code')),
                ('salt', models.CharField(max_length=32, verbose_name='sel')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expire le')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='tentatives maximales')),
                ('resend_count', models.PositiveSmallIntegerField(default=0, verbose_name='renvois')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('invalidated_at', models.DateTimeField(blank=True, null=True, verbose_name='invalidé le')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='agent utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'code OTP',
                'verbose_name_plural': 'codes OTP',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=160, verbose_name='libellé')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='catégorie')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ('category', 'code'),
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='téléphone')),
                ('purpose', models.CharField(choices=[('REGISTER', 'Inscription'), ('LOGIN', 'Connexion'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe'), ('PHONE_CHANGE', 'Changement de numéro'), ('SENSITIVE_ACTION', 'Action sensible')], max_length=20, verbose_name='objet')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='vérifié le')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
            ],
            options={
                'verbose_name': 'vérification téléphone',
                'verbose_name_plural': 'vérifications téléphone',
                'ordering': ('-verified_at',),
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur KEMTA'), ('MANAGER', 'Chargé de suivi KEMTA'), ('FIELD', 'Technicien terrain KEMTA'), ('CUSTOMER', 'Client / propriétaire'), ('COMPANY', 'Entreprise BTP')], max_length=20, verbose_name='rôle')),
                ('allowed', models.BooleanField(default=True, verbose_name='autorisée')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'permission de rôle',
                'verbose_name_plural': 'permissions de rôle',
            },
        ),
    ]
