# Generated by Django 5.1.6 on 2026-10-05 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Renseigné lorsque le code concerne un compte existant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
