# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='libellé')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='famille')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': "corps d'état",
                'verbose_name_plural': "corps d'état",
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nom commercial')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='adresse publique')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='raison sociale')),
                ('registration_number', models.CharField(blank=True, max_length=80, verbose_name='numéro de registre de commerce')),
                ('tax_number', models.CharField(blank=True, max_length=80, verbose_name='numéro contribuable')),
                ('phone', models.CharField(max_length=20, verbose_name='téléphone professionnel')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, verbose_name='second numéro')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail professionnel')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('city', models.CharField(max_length=120, verbose_name='ville')),
                ('region', models.CharField(blank=True, choices=[('AD', 'Adamaoua'), ('CE', 'Centre'), ('ES', 'Est'), ('EN', 'Extrême-Nord'), ('LT', 'Littoral'), ('NO', 'Nord'), ('NW', 'Nord-Ouest'), ('OU', 'Ouest'), ('SU', 'Sud'), ('SW', 'Sud-Ouest')], max_length=2, verbose_name='région')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('country', models.CharField(choices=[('CM', 'Cameroun'), ('FR', 'France'), ('BE', 'Belgique'), ('US', 'États-Unis'), ('CA', 'Canada'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('CH', 'Suisse'), ('GA', 'Gabon'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('NG', 'Nigeria'), ('GQ', 'Guinée équatoriale'), ('TD', 'Tchad'), ('OT', 'Autre')], default='CM', max_length=2, verbose_name='pays')),
                ('description', models.TextField(blank=True, verbose_name='présentation')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(80)], verbose_name="années d'expérience")),
                ('employees_count', models.PositiveSmallIntegerField(default=1, verbose_name='effectif')),
                ('projects_count', models.PositiveIntegerField(default=0, verbose_name='projets réalisés')),
                ('equipment_summary', models.CharField(blank=True, max_length=255, verbose_name='moyens techniques')),
                ('intervention_regions', models.JSONField(blank=True, default=list, help_text="Liste de codes régions ou villes, ex. ['CE', 'LT', 'Yaoundé']", verbose_name="zones d'intervention")),
                ('intervention_radius_km', models.PositiveIntegerField(default=50, verbose_name="rayon d'intervention (km)")),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente de vérification'), ('VERIFIED', 'Entreprise vérifiée'), ('REJECTED', 'Dossier à compléter'), ('SUSPENDED', 'Suspendue')], db_index=True, default='PENDING', max_length=20, verbose_name='statut de vérification')),
                ('verification_notes', models.TextField(blank=True, verbose_name='notes de vérification')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='vérifiée le')),
                ('is_published', models.BooleanField(default=False, verbose_name='visible dans le catalogue')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mise en avant')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note moyenne')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'avis")),
                ('completed_projects_count', models.PositiveIntegerField(default=0, verbose_name='chantiers suivis via KEMTA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_covers', to='common.asset', verbose_name='photo de couverture')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logos', to='common.asset', verbose_name='logo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='responsable du compte')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_companies', to=settings.AUTH_USER_MODEL, verbose_name='vérifiée par')),
            ],
            options={
                'verbose_name': 'entreprise BTP',
                'verbose_name_plural': 'entreprises BTP',
                'ordering': ('-is_featured', '-rating_average', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REGISTRE_COMMERCE', 'Registre de commerce'), ('ATTESTATION_FISCALE', 'Attestation de conformité fiscale'), ('CNPS', 'Attestation CNPS'), ('ASSURANCE', "Attestation d'assurance"), ('REFERENCE', 'Référence / attestation de bonne exécution'), ('PLAN', 'Plan ou devis type'), ('OTHER', 'Autre document')], max_length=30, verbose_name='type')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='intitulé')),
                ('reference_number', models.CharField(blank=True, max_length=120, verbose_name='numéro du document')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='date de délivrance')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name="date d'expiration")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=20, verbose_name='statut')),
                ('review_notes', models.CharField(blank=True, max_length=255, verbose_name='retour KEMTA')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='examiné le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_documents', to='common.asset', verbose_name='fichier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='entreprise')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "document d'entreprise",
                'verbose_name_plural': "documents d'entreprise",
                'ordering': ('kind', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('MANAGER', 'Gérant'), ('EDITOR', 'Éditeur du catalogue'), ('FIELD', 'Conducteur de travaux'), ('VIEWER', 'Observateur')], default='OWNER', max_length=20, verbose_name='rôle')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='fonction')),
                ('can_publish_catalog', models.BooleanField(default=True, verbose_name='peut publier au catalogue')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='a rejoint le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company', verbose_name='entreprise')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invité par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "membre d'entreprise",
                'verbose_name_plural': "membres d'entreprise",
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('work_quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="qualité d'exécution")),
                ('deadline_respect', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='respect des délais')),
                ('communication', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='communication')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié')),
                ('response', models.TextField(blank=True, verbose_name="réponse de l'entreprise")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company', verbose_name='entreprise')),
            ],
            options={
                'verbose_name': 'avis entreprise',
                'verbose_name_plural': 'avis entreprises',
                'ordering': ('-created_at',),
            },
        ),
    ]
