# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_reviews', to='projects.project', verbose_name='projet concerné'),
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['is_active', 'order'], name='companies_s_is_acti_f43853_idx'),
        ),
        migrations.AddField(
            model_name='company',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='companies', to='companies.specialty', verbose_name="corps d'état"),
        ),
        migrations.AddIndex(
            model_name='companydocument',
            index=models.Index(fields=['company', 'status'], name='companies_c_company_772916_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['user', 'is_active'], name='companies_c_user_id_c0b50e_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymember',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_company_member'),
        ),
        migrations.AddIndex(
            model_name='companyreview',
            index=models.Index(fields=['company', 'is_published'], name='companies_c_company_615801_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyreview',
            constraint=models.UniqueConstraint(fields=('company', 'author', 'project'), name='uniq_review_per_project'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['verification_status', 'is_published'], name='companies_c_verific_d66c62_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['city'], name='companies_c_city_42f3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='companies_c_slug_45751b_idx'),
        ),
    ]
