# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('presentation', models.TextField(verbose_name="présentation de l'entreprise et motivation")),
                ('similar_experience', models.TextField(blank=True, verbose_name='expériences similaires')),
                ('methodology', models.TextField(blank=True, verbose_name='méthodologie et organisation prévues')),
                ('estimated_budget_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget estimatif (FCFA)')),
                ('proposed_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='délai proposé (jours)')),
                ('team_size', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='effectif mobilisable')),
                ('team_composition', models.CharField(blank=True, max_length=255, verbose_name="composition de l'équipe")),
                ('message', models.TextField(blank=True, verbose_name='message complémentaire')),
                ('accepts_site_visit', models.BooleanField(default=True, verbose_name='accepte une visite de site')),
                ('contact_override', models.CharField(blank=True, max_length=180, verbose_name='contact pour ce dossier')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Candidature reçue'), ('REVIEWING', "En cours d'examen"), ('SHORTLISTED', 'Présélectionnée'), ('INTERVIEW', 'Entretien / visite programmée'), ('AWARDED', 'Retenue'), ('REJECTED', 'Non retenue'), ('WITHDRAWN', "Retirée par l'entreprise")], db_index=True, default='SUBMITTED', max_length=16, verbose_name='statut')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="note d'évaluation")),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes KEMTA')),
                ('client_feedback', models.TextField(blank=True, verbose_name='retour du client')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='motif de non-retenue')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='instruite le')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='décision le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'candidature BTP',
                'verbose_name_plural': 'candidatures BTP',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('QUOTE', 'Devis estimatif'), ('SCHEDULE', 'Planning prévisionnel'), ('REFERENCE', 'Attestation de référence'), ('TECHNICAL', 'Note technique'), ('ADMIN', 'Document administratif'), ('OTHER', 'Autre')], default='OTHER', max_length=16, verbose_name='type')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='intitulé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pièce de candidature',
                'verbose_name_plural': 'pièces de candidature',
                'ordering': ('kind', 'id'),
            },
        ),
    ]
