# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('btp_catalog', '0002_initial'),
        ('common', '0001_initial'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity', verbose_name='opportunité'),
        ),
        migrations.AddField(
            model_name='application',
            name='relevant_realizations',
            field=models.ManyToManyField(blank=True, related_name='applications', to='btp_catalog.realization', verbose_name='réalisations pertinentes'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='instruite par'),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_applications', to=settings.AUTH_USER_MODEL, verbose_name='déposée par'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application', verbose_name='candidature'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='common.asset', verbose_name='fichier'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-created_at'], name='application_status_db7a61_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['company', '-created_at'], name='application_company_113326_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['opportunity', 'status'], name='application_opportu_56305f_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('opportunity', 'company'), name='uniq_application_per_company'),
        ),
    ]
