# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True, verbose_name='clé')),
                ('label', models.CharField(blank=True, max_length=180, verbose_name='libellé')),
                ('value', models.JSONField(default=dict, verbose_name='valeur')),
                ('is_public', models.BooleanField(default=False, verbose_name='exposé publiquement')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paramètre',
                'verbose_name_plural': 'paramètres',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='TrustStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='libellé')),
                ('value', models.CharField(max_length=40, verbose_name='valeur affichée')),
                ('hint', models.CharField(blank=True, max_length=160, verbose_name='précision')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'chiffre de confiance',
                'verbose_name_plural': 'chiffres de confiance',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document')], default='IMAGE', max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('READY', 'Prêt'), ('FAILED', 'Échec')], default='PENDING', max_length=20, verbose_name='état')),
                ('bucket', models.CharField(blank=True, max_length=120, verbose_name='bucket')),
                ('key', models.CharField(db_index=True, max_length=400, verbose_name='clé objet')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name="nom d'origine")),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='type MIME')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='taille (octets)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='largeur')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='hauteur')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='empreinte')),
                ('variants', models.JSONField(blank=True, default=dict, verbose_name='variantes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='déposé par')),
            ],
            options={
                'verbose_name': 'fichier',
                'verbose_name_plural': 'fichiers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Général', max_length=80, verbose_name='catégorie')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', models.TextField(verbose_name='réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'question FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='common_faqi_is_acti_b85e0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=140, unique=True, verbose_name='clé')),
                ('scope', models.CharField(max_length=80, verbose_name='périmètre')),
                ('response_status', models.PositiveSmallIntegerField(default=0, verbose_name='statut')),
                ('response_body', models.JSONField(blank=True, default=dict, verbose_name='réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "clé d'idempotence",
                'verbose_name_plural': "clés d'idempotence",
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='région / province')),
                ('country', models.CharField(default='CM', max_length=2, verbose_name='pays')),
                ('kind', models.CharField(choices=[('REGION', 'Région'), ('CITY', 'Ville'), ('NEIGHBOURHOOD', 'Quartier'), ('DIASPORA_CITY', 'Ville de la diaspora')], default='CITY', max_length=20, verbose_name='type')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'localisation',
                'verbose_name_plural': 'localisations',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['country', 'kind', 'is_active'], name='common_loca_country_c3f2b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'country', 'kind'), name='uniq_location_name')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=16, verbose_name='préfixe')),
                ('year', models.PositiveIntegerField(verbose_name='année')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='dernier numéro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'compteur de référence',
                'verbose_name_plural': 'compteurs de référence',
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='uniq_reference_counter')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, verbose_name='nom')),
                ('author_role', models.CharField(blank=True, max_length=160, verbose_name='fonction / contexte')),
                ('author_city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('author_country', models.CharField(default='CM', max_length=2, verbose_name='pays')),
                ('quote', models.TextField(verbose_name='témoignage')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='note')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.asset', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'témoignage',
                'verbose_name_plural': 'témoignages',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
