# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='projects.project', verbose_name='projet lié'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['kind', 'status'], name='common_asse_kind_838fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='common_asse_uploade_fcae46_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['scope', '-created_at'], name='common_idem_scope_ac80a8_idx'),
        ),
    ]
