# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('OWNER_LOCAL', 'Propriétaire résidant au Cameroun'), ('DIASPORA', 'Propriétaire de la diaspora'), ('INVESTOR', 'Investisseur'), ('INSTITUTION', 'Institution / entreprise cliente'), ('FAMILY_PROXY', 'Représentant familial')], db_index=True, default='OWNER_LOCAL', max_length=20, verbose_name='type de client')),
                ('country_of_residence', models.CharField(choices=[('CM', 'Cameroun'), ('FR', 'France'), ('BE', 'Belgique'), ('US', 'États-Unis'), ('CA', 'Canada'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('CH', 'Suisse'), ('GA', 'Gabon'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('NG', 'Nigeria'), ('GQ', 'Guinée équatoriale'), ('TD', 'Tchad'), ('OT', 'Autre')], default='CM', max_length=2, verbose_name='pays de résidence')),
                ('city_of_residence', models.CharField(blank=True, max_length=120, verbose_name='ville de résidence')),
                ('whatsapp', models.CharField(blank=True, max_length=24, verbose_name='WhatsApp')),
                ('timezone_name', models.CharField(default='Africa/Douala', max_length=64, verbose_name='fuseau horaire')),
                ('preferred_contact', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'E-mail'), ('PHONE', 'Appel')], default='WHATSAPP', max_length=20, verbose_name='canal de contact préféré')),
                ('occupation', models.CharField(blank=True, max_length=120, verbose_name='profession')),
                ('notes', models.TextField(blank=True, verbose_name='notes internes KEMTA')),
                ('onboarded_at', models.DateTimeField(blank=True, null=True, verbose_name='accompagné depuis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil client',
                'verbose_name_plural': 'profils clients',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='nom complet')),
                ('phone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('relation', models.CharField(choices=[('FAMILY', 'Famille'), ('GUARDIAN', 'Gardien'), ('LOCAL_MANAGER', 'Gestionnaire local'), ('LAWYER', 'Notaire / avocat'), ('OTHER', 'Autre')], default='FAMILY', max_length=20, verbose_name='lien')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('can_receive_keys', models.BooleanField(default=False, verbose_name='peut réceptionner les clés')),
                ('can_authorize_work', models.BooleanField(default=False, verbose_name='peut autoriser des travaux')),
                ('is_primary', models.BooleanField(default=False, verbose_name='contact principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='customers.customerprofile', verbose_name='client')),
            ],
            options={
                'verbose_name': 'contact terrain',
                'verbose_name_plural': 'contacts terrain',
                'ordering': ('-is_primary', 'full_name'),
            },
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['customer_type'], name='customers_c_custome_50dcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['country_of_residence'], name='customers_c_country_42e40a_idx'),
        ),
        migrations.AddConstraint(
            model_name='beneficiary',
            constraint=models.UniqueConstraint(fields=('customer', 'phone'), name='uniq_beneficiary_phone_per_customer'),
        ),
    ]
