# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Consultation'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('EXPORT', 'Export de données'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PERMISSION_DENIED', 'Accès refusé'), ('CONFIG_CHANGE', 'Modification de configuration'), ('PAYMENT', 'Opération de paiement'), ('VERIFY', 'Validation'), ('IMPERSONATE', 'Accès délégué')], db_index=True, max_length=20, verbose_name='action')),
                ('entity_type', models.CharField(blank=True, max_length=60, verbose_name="type d'objet")),
                ('entity_id', models.CharField(blank=True, max_length=60, verbose_name="identifiant d'objet")),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='modifications')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='chemin')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='méthode HTTP')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='code de réponse')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='agent utilisateur')),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='identifiant de trace')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journaux d'audit",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('REQUEST_RECEIVED', 'Demande reçue'), ('REQUEST_STATUS_CHANGED', 'Statut de demande modifié'), ('REQUEST_ASSIGNED', 'Demande assignée'), ('PROJECT_CREATED', 'Projet créé'), ('PROJECT_UPDATED', 'Projet mis à jour'), ('PROJECT_STATUS_CHANGED', 'Statut du projet modifié'), ('PHASE_UPDATED', 'Étape mise à jour'), ('TASK_CREATED', 'Tâche créée'), ('TASK_COMPLETED', 'Tâche terminée'), ('EVIDENCE_UPLOADED', 'Preuve déposée'), ('EVIDENCE_VALIDATED', 'Preuve validée'), ('EVIDENCE_REJECTED', 'Preuve refusée'), ('REPORT_CREATED', 'Rapport rédigé'), ('REPORT_VALIDATED', 'Rapport validé'), ('DOCUMENT_UPLOADED', 'Document déposé'), ('PAYMENT_INITIATED', 'Paiement initié'), ('PAYMENT_SUCCEEDED', 'Paiement encaissé'), ('PAYMENT_FAILED', 'Paiement échoué'), ('INVOICE_CREATED', 'Facture émise'), ('SUBSCRIPTION_CHANGED', 'Abonnement modifié'), ('COMPANY_CREATED', 'Entreprise créée'), ('COMPANY_VERIFIED', 'Entreprise vérifiée'), ('COMPANY_REJECTED', 'Dossier entreprise à compléter'), ('CATALOG_PUBLISHED', 'Réalisation publiée'), ('CATALOG_UPDATED', 'Réalisation mise à jour'), ('OPPORTUNITY_CREATED', 'Opportunité publiée'), ('APPLICATION_SUBMITTED', 'Candidature déposée'), ('APPLICATION_STATUS_CHANGED', 'Statut de candidature modifié'), ('PROPERTY_CREATED', 'Propriété enregistrée'), ('VISIT_SCHEDULED', 'Visite planifiée'), ('VISIT_COMPLETED', 'Visite réalisée'), ('ISSUE_REPORTED', 'Problème signalé'), ('MEMBER_ADDED', 'Membre ajouté'), ('LOGIN', 'Connexion'), ('SETTINGS_CHANGED', 'Paramètres modifiés')], db_index=True, max_length=32, verbose_name='action')),
                ('message', models.CharField(max_length=255, verbose_name='libellé affichable')),
                ('entity_type', models.CharField(blank=True, max_length=40, verbose_name="type d'objet")),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name="identifiant d'objet")),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='lien')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='données')),
                ('visibility', models.CharField(choices=[('CUSTOMER', 'Client'), ('TEAM', 'Équipe KEMTA'), ('PUBLIC', 'Public')], default='TEAM', max_length=10, verbose_name='visibilité')),
                ('is_important', models.BooleanField(default=False, verbose_name='événement marquant')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='agent utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'ordering': ('-created_at',),
            },
        ),
    ]
