# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='date du rapport')),
                ('weather', models.CharField(choices=[('SUNNY', 'Ensoleillé'), ('CLOUDY', 'Nuageux'), ('RAINY', 'Pluvieux'), ('STORM', 'Orage'), ('HEATWAVE', 'Forte chaleur')], default='SUNNY', max_length=10, verbose_name='météo')),
                ('workers_count', models.PositiveSmallIntegerField(default=0, verbose_name='effectif présent')),
                ('supervisors_count', models.PositiveSmallIntegerField(default=0, verbose_name='encadrement présent')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='avancement constaté (%)')),
                ('works_done', models.TextField(blank=True, verbose_name='travaux réalisés')),
                ('works_planned', models.TextField(blank=True, verbose_name='travaux prévus demain')),
                ('blockers', models.TextField(blank=True, verbose_name='difficultés rencontrées')),
                ('decisions_needed', models.TextField(blank=True, verbose_name='décisions attendues du client')),
                ('materials_received', models.JSONField(blank=True, default=list, verbose_name='matériaux reçus')),
                ('equipment_used', models.CharField(blank=True, max_length=255, verbose_name='matériel utilisé')),
                ('safety_notes', models.CharField(blank=True, max_length=255, verbose_name='consignes / sécurité')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='heures travaillées')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('is_visible_to_customer', models.BooleanField(default=False, verbose_name='visible par le client')),
                ('client_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='vu par le client le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='rédigé par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project', verbose_name='projet')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'rapport journalier',
                'verbose_name_plural': 'rapports journaliers',
                'ordering': ('-report_date',),
                'indexes': [models.Index(fields=['project', '-report_date'], name='reports_dai_project_f32e7a_idx'), models.Index(fields=['is_visible_to_customer', '-report_date'], name='reports_dai_is_visi_1e4814_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'report_date'), name='uniq_daily_report')],
            },
        ),
        migrations.CreateModel(
            name='PeriodicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('PHASE', 'Fin de phase'), ('FINAL', 'Réception / rapport final'), ('CUSTOM', 'Sur mesure')], default='WEEKLY', max_length=8, verbose_name='périodicité')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('period_start', models.DateField(verbose_name='début de période')),
                ('period_end', models.DateField(verbose_name='fin de période')),
                ('summary', models.TextField(blank=True, verbose_name='synthèse')),
                ('progress_snapshot', models.JSONField(blank=True, default=dict, verbose_name='indicateurs')),
                ('highlights', models.JSONField(blank=True, default=list, verbose_name='points marquants')),
                ('risks', models.JSONField(blank=True, default=list, verbose_name='risques et alertes')),
                ('next_steps', models.JSONField(blank=True, default=list, verbose_name='prochaines étapes')),
                ('financial_summary', models.JSONField(blank=True, default=dict, verbose_name='synthèse financière')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('GENERATING', 'Génération en cours'), ('READY', 'Prêt'), ('SENT', 'Transmis au client'), ('FAILED', 'Échec de génération')], default='DRAFT', max_length=12, verbose_name='statut')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='généré le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='transmis le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_reports', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_reports', to='common.asset', verbose_name='PDF généré')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_reports', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'rapport périodique',
                'verbose_name_plural': 'rapports périodiques',
                'ordering': ('-period_end', '-created_at'),
                'indexes': [models.Index(fields=['project', '-period_end'], name='reports_per_project_394517_idx'), models.Index(fields=['status', '-created_at'], name='reports_per_status_249143_idx')],
            },
        ),
    ]
