# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('kind', models.CharField(choices=[('SUBSCRIPTION', 'Abonnement entreprise'), ('INVOICE', 'Règlement de facture'), ('MILESTONE', 'Décaissement par jalon'), ('ESCROW_FUNDING', 'Alimentation du compte séquestre'), ('SERVICE_FEE', 'Frais de service KEMTA'), ('OTHER', 'Autre')], default='OTHER', max_length=16, verbose_name='nature')),
                ('provider', models.CharField(choices=[('MANUAL', 'Virement / espèces (hors ligne)'), ('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('CARD', 'Carte bancaire'), ('BANK_TRANSFER', 'Virement bancaire'), ('OTHER', 'Autre fournisseur')], default='MANUAL', max_length=16, verbose_name='fournisseur')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('SUCCEEDED', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé'), ('EXPIRED', 'Expiré')], db_index=True, default='PENDING', max_length=12, verbose_name='statut')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA (XAF)'), ('EUR', 'Euro'), ('USD', 'Dollar américain')], default='XAF', max_length=3, verbose_name='devise')),
                ('amount_xaf', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant (FCFA)')),
                ('idempotency_key', models.CharField(help_text='Empêche tout double débit en cas de double envoi du formulaire.', max_length=140, unique=True, verbose_name="clé d'idempotence")),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='référence fournisseur')),
                ('payer_phone', models.CharField(blank=True, max_length=20, verbose_name='numéro de paiement')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de reçu')),
                ('checkout_url', models.URLField(blank=True, verbose_name='lien de paiement')),
                ('instructions', models.CharField(blank=True, max_length=255, verbose_name='instructions de paiement')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name="motif d'échec")),
                ('refunded_amount_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant remboursé')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payé le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expire le')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('SUCCEEDED', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé'), ('EXPIRED', 'Expiré')], max_length=12, verbose_name='statut')),
                ('provider', models.CharField(choices=[('MANUAL', 'Virement / espèces (hors ligne)'), ('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('CARD', 'Carte bancaire'), ('BANK_TRANSFER', 'Virement bancaire'), ('OTHER', 'Autre fournisseur')], max_length=16, verbose_name='fournisseur')),
                ('provider_event', models.CharField(blank=True, max_length=60, verbose_name='événement')),
                ('provider_event_id', models.CharField(max_length=160, unique=True, verbose_name="identifiant d'événement")),
                ('provider_transaction_id', models.CharField(blank=True, max_length=160, verbose_name='transaction fournisseur')),
                ('amount_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant')),
                ('fees_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='frais')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='charge utile')),
                ('signature_verified', models.BooleanField(default=False, verbose_name='signature vérifiée')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name="motif d'échec")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'transaction de paiement',
                'verbose_name_plural': 'transactions de paiement',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('label', models.CharField(max_length=200, verbose_name='objet')),
                ('amount_xaf', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant')),
                ('status', models.CharField(choices=[('REQUESTED', 'Demandé'), ('APPROVED', 'Approuvé'), ('PAID', 'Payé'), ('REJECTED', 'Refusé')], db_index=True, default='REQUESTED', max_length=10, verbose_name='statut')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payé le')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'décaissement',
                'verbose_name_plural': 'décaissements',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MANUAL', 'Virement / espèces (hors ligne)'), ('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('CARD', 'Carte bancaire'), ('BANK_TRANSFER', 'Virement bancaire'), ('OTHER', 'Autre fournisseur')], max_length=16, verbose_name='fournisseur')),
                ('event_id', models.CharField(max_length=160, unique=True, verbose_name='identifiant')),
                ('event_type', models.CharField(blank=True, max_length=80, verbose_name='type')),
                ('payload', models.JSONField(default=dict, verbose_name='charge utile')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='signature valide')),
                ('processed', models.BooleanField(default=False, verbose_name='traité')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='erreur')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'notification fournisseur',
                'verbose_name_plural': 'notifications fournisseur',
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='numéro')),
                ('kind', models.CharField(choices=[('SUBSCRIPTION', 'Abonnement entreprise'), ('INVOICE', 'Règlement de facture'), ('MILESTONE', 'Décaissement par jalon'), ('ESCROW_FUNDING', 'Alimentation du compte séquestre'), ('SERVICE_FEE', 'Frais de service KEMTA'), ('OTHER', 'Autre')], default='OTHER', max_length=16, verbose_name='nature')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA (XAF)'), ('EUR', 'Euro'), ('USD', 'Dollar américain')], default='XAF', max_length=3, verbose_name='devise')),
                ('subtotal_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant HT')),
                ('tax_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('total_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('amount_paid_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='déjà réglé')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PARTIALLY_PAID', 'Partiellement réglée'), ('PAID', 'Réglée'), ('OVERDUE', 'En retard'), ('VOID', 'Annulée')], db_index=True, default='DRAFT', max_length=16, verbose_name='statut')),
                ('lines', models.JSONField(blank=True, default=list, help_text='Liste [{label, quantity, unit_price, total}] pour le PDF.', verbose_name='lignes')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='mentions')),
                ('issued_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='émise le')),
                ('due_at', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='réglée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='companies.company', verbose_name='entreprise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='common.asset', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ('-issued_at', '-id'),
            },
        ),
    ]
