# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='référence')),
                ('title', models.CharField(max_length=200, verbose_name='intitulé du marché')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='adresse')),
                ('description', models.TextField(verbose_name='description du besoin')),
                ('scope_of_work', models.TextField(blank=True, verbose_name='travaux attendus')),
                ('required_documents', models.JSONField(blank=True, default=list, verbose_name='pièces demandées')),
                ('property_type', models.CharField(choices=[('VILLA', 'Villa'), ('MAISON', 'Maison'), ('IMMEUBLE', 'Immeuble'), ('APPARTEMENT', 'Appartements'), ('LOCAL_COMMERCIAL', 'Local commercial'), ('ECOLE', 'École'), ('SANTE', 'Structure de santé'), ('ROUTE', 'Voirie'), ('FORAGE', 'Forage / eau'), ('RENOVATION', 'Rénovation'), ('AMENAGEMENT', 'Aménagement'), ('AUTRE', 'Autre')], default='VILLA', max_length=40, verbose_name='type de bien')),
                ('location_text', models.CharField(blank=True, max_length=180, verbose_name='localisation affichée')),
                ('country', models.CharField(choices=[('CM', 'Cameroun'), ('FR', 'France'), ('BE', 'Belgique'), ('US', 'États-Unis'), ('CA', 'Canada'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('CH', 'Suisse'), ('GA', 'Gabon'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('NG', 'Nigeria'), ('GQ', 'Guinée équatoriale'), ('TD', 'Tchad'), ('OT', 'Autre')], default='CM', max_length=2, verbose_name='pays')),
                ('site_available_for_visit', models.BooleanField(default=True, verbose_name='visite du site possible')),
                ('budget_min_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget indicatif minimum (FCFA)')),
                ('budget_max_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget indicatif maximum (FCFA)')),
                ('budget_visible', models.BooleanField(default=True, verbose_name='afficher le budget indicatif')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='démarrage souhaité')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée estimée (jours)')),
                ('application_deadline', models.DateField(db_index=True, verbose_name='date limite de candidature')),
                ('minimum_experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='expérience minimale (années)')),
                ('requires_verified_company', models.BooleanField(default=True, verbose_name='réservée aux entreprises vérifiées')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouverte aux candidatures'), ('CLOSED', 'Clôturée'), ('REVIEWING', "En cours d'analyse"), ('AWARDED', 'Attribuée'), ('CANCELLED', 'Annulée')], db_index=True, default='DRAFT', max_length=16, verbose_name='statut')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Visible par tous'), ('REGISTERED', 'Réservée aux entreprises inscrites'), ('VERIFIED', 'Réservée aux entreprises vérifiées'), ('INVITED', 'Sur invitation KEMTA')], default='PUBLIC', max_length=16, verbose_name='visibilité')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mise en avant')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publiée le')),
                ('client_name', models.CharField(blank=True, max_length=180, verbose_name='client (interne)')),
                ('client_contact', models.CharField(blank=True, max_length=180, verbose_name='contact client (interne)')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('applications_count', models.PositiveIntegerField(default=0, verbose_name='candidatures reçues')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='common.location', verbose_name='localisation')),
            ],
            options={
                'verbose_name': 'opportunité BTP',
                'verbose_name_plural': 'opportunités BTP',
                'ordering': ('-is_featured', '-published_at', '-created_at'),
            },
        ),
    ]
