# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('opportunities', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='projects.project', verbose_name='projet lié'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='required_specialties',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='companies.specialty', verbose_name="corps d'état requis"),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'application_deadline'], name='opportuniti_status_b8e4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'visibility', '-published_at'], name='opportuniti_status_d1008a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['property_type', 'status'], name='opportuniti_propert_910798_idx'),
        ),
    ]
