# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('construction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='message')),
                ('is_internal', models.BooleanField(default=False, verbose_name='note interne KEMTA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'commentaire de preuve',
                'verbose_name_plural': 'commentaires de preuve',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document'), ('NOTE', 'Note de terrain'), ('MEASUREMENT', 'Relevé / mesure'), ('INCIDENT', 'Incident')], default='PHOTO', max_length=12, verbose_name='type')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='titre')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='légende')),
                ('note', models.TextField(blank=True, verbose_name='observation')),
                ('measurements', models.JSONField(blank=True, default=dict, verbose_name='relevés')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='prise le (appareil)')),
                ('capture_device', models.CharField(blank=True, max_length=120, verbose_name='appareil')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('accuracy_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='précision GPS (m)')),
                ('distance_to_site_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='distance au site (m)')),
                ('is_offline_capture', models.BooleanField(default=False, verbose_name='capturée hors ligne')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identifiant client')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('VALIDATED', 'Validée'), ('REJECTED', 'Refusée'), ('ARCHIVED', 'Archivée')], db_index=True, default='PENDING', max_length=12, verbose_name='statut')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='motif de refus')),
                ('is_visible_to_customer', models.BooleanField(default=True, verbose_name='visible par le client')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='reçue le')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='common.asset', verbose_name='fichier')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_evidences', to=settings.AUTH_USER_MODEL, verbose_name='capturée par')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='construction.phase', verbose_name='phase')),
            ],
            options={
                'verbose_name': 'preuve terrain',
                'verbose_name_plural': 'preuves terrain',
                'ordering': ('-captured_at', '-created_at'),
            },
        ),
    ]
