# Generated by Django 5.1.6 on 2026-10-05 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidences', '0001_initial'),
        ('projects', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='projects.project', verbose_name='projet'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='properties.property', verbose_name='propriété'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='projects.task', verbose_name='tâche'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL, verbose_name='déposée par'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_evidences', to=settings.AUTH_USER_MODEL, verbose_name='validée par'),
        ),
        migrations.AddField(
            model_name='evidencecomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_comments', to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AddField(
            model_name='evidencecomment',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='evidences.evidence', verbose_name='preuve'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['project', 'status', '-created_at'], name='evidences_e_project_7d9552_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['project', 'kind'], name='evidences_e_project_fe195f_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['property', '-created_at'], name='evidences_e_propert_0fd92a_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['status', '-created_at'], name='evidences_e_status_e5ff30_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', False), ('property__isnull', False), _connector='OR'), name='evidence_requires_project_or_property'),
        ),
        migrations.AddIndex(
            model_name='evidencecomment',
            index=models.Index(fields=['evidence', 'created_at'], name='evidences_e_evidenc_590d3a_idx'),
        ),
    ]
